<?php
/**
 * LibrariesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mzk\ZiskejApiClientSwagger
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ziskej API
 *
 * Client PHP for Ziskej API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Mzk\ZiskejApiClientSwagger;

use Mzk\ZiskejApiClientSwagger\Configuration;
use Mzk\ZiskejApiClientSwagger\ApiException;
use Mzk\ZiskejApiClientSwagger\ObjectSerializer;

/**
 * LibrariesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mzk\ZiskejApiClientSwagger
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LibrariesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for librariesGet
     *
     * Libraries.
     *
     */
    public function testLibrariesGet()
    {
    }
}
